FROM node:18.17.0

FROM node:18.17.0 as builder

# Updates packages, install google-chrome-stable and dependencies.
RUN apt-get update -y \
  && apt-get install curl gnupg2 apt-transport-https ca-certificates wget --no-install-recommends -y \
  && curl -sSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
  && apt-get update -y \
  --no-install-recommends

# Installs dumb-init (basic entrypoint with signals handling and forwarding).
RUN wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_120.0.6099.71-1_amd64.deb
RUN apt-get install ./google-chrome-stable_120.0.6099.71-1_amd64.deb -y --no-install-recommends

# Change to yarn if you need it.
RUN npm install http-server -g

WORKDIR /app

# Move our files into directory name "app"
COPY .  .

# RUN npm i @babel/traverse
RUN npm i
RUN npm run build

EXPOSE 8080

CMD [ "http-server", "dist" ]